// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Dialog = "_Dialog";
                public readonly string _Layout = "_Layout";
                public readonly string _Menu = "_Menu";
                public readonly string _Nav = "_Nav";
                public readonly string _OnlineUsers = "_OnlineUsers";
                public readonly string _Pagination = "_Pagination";
                public readonly string _SocialButtons = "_SocialButtons";
                public readonly string _UserMenu = "_UserMenu";
                public readonly string Error = "Error";
            }
            public readonly string _Dialog = "~/Views/Shared/_Dialog.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _Menu = "~/Views/Shared/_Menu.cshtml";
            public readonly string _Nav = "~/Views/Shared/_Nav.cshtml";
            public readonly string _OnlineUsers = "~/Views/Shared/_OnlineUsers.cshtml";
            public readonly string _Pagination = "~/Views/Shared/_Pagination.cshtml";
            public readonly string _SocialButtons = "~/Views/Shared/_SocialButtons.cshtml";
            public readonly string _UserMenu = "~/Views/Shared/_UserMenu.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string DateTime = "DateTime";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
