// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MirGames.Controllers
{
    public partial class UsersController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UsersController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Profile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Profile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Topics()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Topics);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Comments()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Forum()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Forum);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewWallRecord()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewWallRecord);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UsersController Actions { get { return MVC.Users; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Users";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Users";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Top = "Top";
            public readonly string NotActivated = "NotActivated";
            public readonly string Online = "Online";
            public readonly string Profile = "Profile";
            public readonly string Topics = "Topics";
            public readonly string Comments = "Comments";
            public readonly string Forum = "Forum";
            public readonly string Settings = "Settings";
            public readonly string Feed = "Feed";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string NewWallRecord = "NewWallRecord";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Top = "Top";
            public const string NotActivated = "NotActivated";
            public const string Online = "Online";
            public const string Profile = "Profile";
            public const string Topics = "Topics";
            public const string Comments = "Comments";
            public const string Forum = "Forum";
            public const string Settings = "Settings";
            public const string Feed = "Feed";
            public const string DeleteUser = "DeleteUser";
            public const string NewWallRecord = "NewWallRecord";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string page = "page";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_Top s_params_Top = new ActionParamsClass_Top();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Top TopParams { get { return s_params_Top; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Top
        {
            public readonly string page = "page";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_NotActivated s_params_NotActivated = new ActionParamsClass_NotActivated();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NotActivated NotActivatedParams { get { return s_params_NotActivated; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NotActivated
        {
            public readonly string page = "page";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_Online s_params_Online = new ActionParamsClass_Online();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Online OnlineParams { get { return s_params_Online; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Online
        {
            public readonly string page = "page";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_Profile s_params_Profile = new ActionParamsClass_Profile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Profile ProfileParams { get { return s_params_Profile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Profile
        {
            public readonly string userId = "userId";
        }
        static readonly ActionParamsClass_Topics s_params_Topics = new ActionParamsClass_Topics();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Topics TopicsParams { get { return s_params_Topics; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Topics
        {
            public readonly string userId = "userId";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Comments s_params_Comments = new ActionParamsClass_Comments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Comments CommentsParams { get { return s_params_Comments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Comments
        {
            public readonly string userId = "userId";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Forum s_params_Forum = new ActionParamsClass_Forum();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Forum ForumParams { get { return s_params_Forum; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Forum
        {
            public readonly string userId = "userId";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Feed s_params_Feed = new ActionParamsClass_Feed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Feed FeedParams { get { return s_params_Feed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Feed
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_NewWallRecord s_params_NewWallRecord = new ActionParamsClass_NewWallRecord();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewWallRecord NewWallRecordParams { get { return s_params_NewWallRecord; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewWallRecord
        {
            public readonly string command = "command";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ProfileMenu = "_ProfileMenu";
                public readonly string _UserInfo = "_UserInfo";
                public readonly string _UserListItem = "_UserListItem";
                public readonly string _UsersMenu = "_UsersMenu";
                public readonly string _WallRecord = "_WallRecord";
                public readonly string Comments = "Comments";
                public readonly string Feed = "Feed";
                public readonly string ForumPosts = "ForumPosts";
                public readonly string Index = "Index";
                public readonly string Profile = "Profile";
                public readonly string Settings = "Settings";
                public readonly string Topics = "Topics";
            }
            public readonly string _ProfileMenu = "~/Views/Users/_ProfileMenu.cshtml";
            public readonly string _UserInfo = "~/Views/Users/_UserInfo.cshtml";
            public readonly string _UserListItem = "~/Views/Users/_UserListItem.cshtml";
            public readonly string _UsersMenu = "~/Views/Users/_UsersMenu.cshtml";
            public readonly string _WallRecord = "~/Views/Users/_WallRecord.cshtml";
            public readonly string Comments = "~/Views/Users/Comments.cshtml";
            public readonly string Feed = "~/Views/Users/Feed.cshtml";
            public readonly string ForumPosts = "~/Views/Users/ForumPosts.cshtml";
            public readonly string Index = "~/Views/Users/Index.cshtml";
            public readonly string Profile = "~/Views/Users/Profile.cshtml";
            public readonly string Settings = "~/Views/Users/Settings.cshtml";
            public readonly string Topics = "~/Views/Users/Topics.cshtml";
            static readonly _FeedItemsClass s_FeedItems = new _FeedItemsClass();
            public _FeedItemsClass FeedItems { get { return s_FeedItems; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _FeedItemsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Chat_UserMentioned = "Chat.UserMentioned";
                    public readonly string Forum_NewAnswer = "Forum.NewAnswer";
                    public readonly string Forum_NewTopic = "Forum.NewTopic";
                    public readonly string Topics_NewBlogTopic = "Topics.NewBlogTopic";
                    public readonly string Topics_NewTopicComment = "Topics.NewTopicComment";
                    public readonly string Wip_NewCommit = "Wip.NewCommit";
                }
                public readonly string Chat_UserMentioned = "~/Views/Users/FeedItems/Chat.UserMentioned.cshtml";
                public readonly string Forum_NewAnswer = "~/Views/Users/FeedItems/Forum.NewAnswer.cshtml";
                public readonly string Forum_NewTopic = "~/Views/Users/FeedItems/Forum.NewTopic.cshtml";
                public readonly string Topics_NewBlogTopic = "~/Views/Users/FeedItems/Topics.NewBlogTopic.cshtml";
                public readonly string Topics_NewTopicComment = "~/Views/Users/FeedItems/Topics.NewTopicComment.cshtml";
                public readonly string Wip_NewCommit = "~/Views/Users/FeedItems/Wip.NewCommit.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UsersController : MirGames.Controllers.UsersController
    {
        public T4MVC_UsersController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int page, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            IndexOverride(callInfo, page, searchString);
            return callInfo;
        }

        [NonAction]
        partial void TopOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult Top(int page, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Top);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            TopOverride(callInfo, page, searchString);
            return callInfo;
        }

        [NonAction]
        partial void NotActivatedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult NotActivated(int page, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NotActivated);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            NotActivatedOverride(callInfo, page, searchString);
            return callInfo;
        }

        [NonAction]
        partial void OnlineOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult Online(int page, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Online);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            OnlineOverride(callInfo, page, searchString);
            return callInfo;
        }

        [NonAction]
        partial void ProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Profile(int userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Profile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ProfileOverride(callInfo, userId);
            return callInfo;
        }

        [NonAction]
        partial void TopicsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Topics(int userId, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Topics);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            TopicsOverride(callInfo, userId, page);
            return callInfo;
        }

        [NonAction]
        partial void CommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Comments(int userId, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            CommentsOverride(callInfo, userId, page);
            return callInfo;
        }

        [NonAction]
        partial void ForumOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Forum(int userId, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Forum);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ForumOverride(callInfo, userId, page);
            return callInfo;
        }

        [NonAction]
        partial void SettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Settings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Settings);
            SettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Feed(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Feed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            FeedOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MirGames.Domain.Users.Commands.DeleteUserCommand command);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteUser(MirGames.Domain.Users.Commands.DeleteUserCommand command)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "command", command);
            DeleteUserOverride(callInfo, command);
            return callInfo;
        }

        [NonAction]
        partial void NewWallRecordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MirGames.Domain.Users.Commands.PostWallRecordCommand command);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewWallRecord(MirGames.Domain.Users.Commands.PostWallRecordCommand command)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewWallRecord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "command", command);
            NewWallRecordOverride(callInfo, command);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
